name = "GPLVM_plus_dataset"
uuid = "9fd33059-656d-4867-a56b-947448e04143"
authors = ["Nikos Gianniotis <ngiann@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
